In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [2]:
df = pd.read_csv(r'measurements.csv')

In [3]:
print(df.head())

  distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
0       28       5     26        21,5            12      NaN      E10   0   
1       12     4,2     30        21,5            13      NaN      E10   0   
2     11,2     5,5     38        21,5            15      NaN      E10   0   
3     12,9     3,9     36        21,5            14      NaN      E10   0   
4     18,5     4,5     46        21,5            15      NaN      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0           NaN        NaN  
2     0    0           NaN        NaN  
3     0    0           NaN        NaN  
4     0    0           NaN        NaN  


In [4]:
df.dtypes

distance         object
consume          object
speed             int64
temp_inside      object
temp_outside      int64
specials         object
gas_type         object
AC                int64
rain              int64
sun               int64
refill liters    object
refill gas       object
dtype: object

In [5]:
df = df.fillna(0)

In [6]:
df.describe

<bound method NDFrame.describe of     distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
0         28       5     26        21,5            12        0      E10   0   
1         12     4,2     30        21,5            13        0      E10   0   
2       11,2     5,5     38        21,5            15        0      E10   0   
3       12,9     3,9     36        21,5            14        0      E10   0   
4       18,5     4,5     46        21,5            15        0      E10   0   
..       ...     ...    ...         ...           ...      ...      ...  ..   
383       16     3,7     39        24,5            18        0     SP98   0   
384     16,1     4,3     38          25            31       AC     SP98   1   
385       16     3,8     45          25            19        0     SP98   0   
386     15,4     4,6     42          25            31       AC     SP98   1   
387     14,7       5     25          25            30       AC     SP98   1   

     rain  sun re

In [7]:
df['consume'] = df['consume'].str.replace(',', ".").astype(float)

In [8]:
df['distance'] = df['distance'].str.replace(',', ".").astype(float)

In [9]:
df['temp_inside'] = df['temp_inside'].str.replace(',', ".").astype(float)

In [10]:
df.head()

distance  consume  speed  temp_inside  temp_outside specials gas_type  AC  \
0      28.0      5.0     26         21.5            12        0      E10   0   
1      12.0      4.2     30         21.5            13        0      E10   0   
2      11.2      5.5     38         21.5            15        0      E10   0   
3      12.9      3.9     36         21.5            14        0      E10   0   
4      18.5      4.5     46         21.5            15        0      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0             0          0  
2     0    0             0          0  
3     0    0             0          0  
4     0    0             0          0

In [11]:
regressor = LinearRegression()  

In [12]:
X = df['distance'].values.reshape(-1,1)
y = df['consume'].values.reshape(-1,1)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
regressor.fit(X_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

[5.009701]
[[-0.00679622]]


In [16]:
y_pred = regressor.predict(X_test)

In [17]:
df_pos = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [18]:
df_pos

Actual  Predicted
0      6.4   4.968244
1      4.6   4.929506
2      5.4   4.981836
3      4.4   4.733774
4      3.8   4.900961
..     ...        ...
73     4.3   4.929506
74    11.5   5.000866
75     5.5   3.903956
76     5.0   4.926107
77     4.3   4.924748

[78 rows x 2 columns]

In [19]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.799361838878688
Mean Squared Error: 1.734971687233217
Root Mean Squared Error: 1.317183239808804


In [25]:
score = regressor.score(X_train,y_train)

In [28]:
print(score*100)

1.9230012975138933


In [86]:
df.head()

distance  consume  speed  temp_inside  temp_outside specials gas_type  AC  \
0      28.0      5.0     26         21.5            12        0      E10   0   
1      12.0      4.2     30         21.5            13        0      E10   0   
2      11.2      5.5     38         21.5            15        0      E10   0   
3      12.9      3.9     36         21.5            14        0      E10   0   
4      18.5      4.5     46         21.5            15        0      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0             0          0  
2     0    0             0          0  
3     0    0             0          0  
4     0    0             0          0

In [104]:
df['consume'] = df['consume'].fillna(0)
df['speed'] = df['speed'].fillna(0)
df['distance'] = df['distance'].fillna(0)
df['temp_inside'] = df['temp_inside'].fillna(0)
df['temp_outside'] = df['temp_outside'].fillna(0)

In [105]:
X = df[['distance', 'speed', 'temp_inside', 'temp_outside']].values
y = df['consume'].values

In [106]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [107]:
regressor.fit(X_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [108]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

5.671475516382248
[ 0.00093101 -0.0136709   0.01475327 -0.04820559]


In [109]:
y_pred = regressor.predict(X_test)

In [110]:
df_pos = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [111]:
df_pos

Actual  Predicted
0      6.4   5.225920
1      4.6   5.502292
2      5.4   5.052467
3      4.4   5.272957
4      3.8   5.078463
..     ...        ...
73     4.3   5.182470
74    11.5   5.198606
75     5.5   5.088753
76     5.0   4.958642
77     4.3   4.464531

[78 rows x 2 columns]

In [112]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.7260254169491258
Mean Squared Error: 1.5159701423481142
Root Mean Squared Error: 1.2312473928289611


In [113]:
X = df[['distance', 'speed']].values
y = df['consume'].values

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [115]:
regressor.fit(X_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [116]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

5.3972831294280565
[-0.00252327 -0.01124035]


In [117]:
y_pred = regressor.predict(X_test)

In [118]:
df_pos = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [119]:
df_pos

Actual  Predicted
0      6.4   5.067161
1      4.6   4.940375
2      5.4   5.117169
3      4.4   4.800263
4      3.8   4.907297
..     ...        ...
73     4.3   4.951615
74    11.5   5.157955
75     5.5   4.143721
76     5.0   4.894152
77     4.3   4.725042

[78 rows x 2 columns]

In [120]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.7770064666034029
Mean Squared Error: 1.6297137002759252
Root Mean Squared Error: 1.2766024049311224


In [121]:
df.head()

distance  consume  speed  temp_inside  temp_outside specials gas_type  AC  \
0      28.0      5.0     26         21.5            12        0      E10   0   
1      12.0      4.2     30         21.5            13        0      E10   0   
2      11.2      5.5     38         21.5            15        0      E10   0   
3      12.9      3.9     36         21.5            14        0      E10   0   
4      18.5      4.5     46         21.5            15        0      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0             0          0  
2     0    0             0          0  
3     0    0             0          0  
4     0    0             0          0

In [127]:
df_gas_type = df['gas_type'].unique()

df_gas_type = pd.DataFrame(df_gas_type, columns=['gas'])

df_gas_type.insert(1, "de_para", ['1', '2']) 

In [128]:
df_gas_type

gas de_para
0   E10       1
1  SP98       2

In [129]:
df_new = df

In [131]:
df_new['gas_type'] = df_new['gas_type'].replace('E10', 1)

df_new['gas_type'] = df_new['gas_type'].replace('SP98', 2)

In [132]:
X = df_new[['distance', 'speed', 'temp_inside', 'temp_outside','gas_type']].values
y = df_new['consume'].values

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [134]:
regressor.fit(X_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [135]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

5.577207949868592
[ 0.0011162  -0.0135752   0.01513346 -0.04899202  0.05490995]


In [136]:
y_pred = regressor.predict(X_test)

In [137]:
df_pos = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [138]:
df_pos

Actual  Predicted
0      6.4   5.247164
1      4.6   5.532411
2      5.4   5.014496
3      4.4   5.250953
4      3.8   5.102879
..     ...        ...
73     4.3   5.206634
74    11.5   5.216149
75     5.5   5.149571
76     5.0   4.926271
77     4.3   4.428914

[78 rows x 2 columns]

In [139]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.7295019768524275
Mean Squared Error: 1.518656169035666
Root Mean Squared Error: 1.2323376846610128


In [140]:
X = df_new[['distance', 'speed','gas_type']].values
y = df_new['consume'].values

In [141]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [142]:
regressor.fit(X_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [143]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

5.556414375139148
[-0.00273895 -0.01146744 -0.09116252]


In [144]:
y_pred = regressor.predict(X_test)

In [145]:
df_pos = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})

In [146]:
df_pos

Actual  Predicted
0      6.4   5.036293
1      4.6   4.906007
2      5.4   5.178804
3      4.4   4.849483
4      3.8   4.871568
..     ...        ...
73     4.3   4.917474
74    11.5   5.129712
75     5.5   4.068404
76     5.0   4.949930
77     4.3   4.777371

[78 rows x 2 columns]